Updated precommit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -14,47 +14,49 @@ then
 fi
 SFILES=${SFILES:-$STAGED_FILES_CMD}
 
-echo "Checking PHP files..."
+if [ -n "$SFILES" ]; then
+    echo "Checking PHP files..."
 
-for FILE in $SFILES
-do
-    php -l -d display_errors=0 $PROJECT/$FILE
-    if [ $? != 0 ]
-    then
-        printf "Fix syntax errors before commit."
-        exit 1
+    for FILE in $SFILES
+    do
+        php -l -d display_errors=0 $PROJECT/$FILE
+        if [ $? != 0 ]
+        then
+            printf "Fix syntax errors before commit."
+            exit 1
+        fi
+        FILES="$FILES $PROJECT/$FILE"
+    done
+
+    PHPSTAN="../../vendor/bin/phpstan"
+
+    if [ -f "$PHPSTAN" ]; then
+        echo ""
+        printf "Running PhpStan..."
+        eval "$PHPSTAN analyze --level 2 --configuration ../../phpstan.neon --no-progress ./"
+        if [ $? != 0 ]
+        then
+            echo "Fix PhpStan errors before commit."
+            echo "Run: '$PHPSTAN analyze'"
+            exit 1
+        fi
     fi
-    FILES="$FILES $PROJECT/$FILE"
-done
 
-PHPSTAN="../../vendor/bin/phpstan"
+    CSFIXER="../../php-cs-fixer.phar"
 
-if [ -f "$PHPSTAN" ]; then
-    echo ""
-    printf "Running PhpStan..."
-	eval "$PHPSTAN analyze --level 2 --configuration ../../phpstan.neon --no-progress ./"
-    if [ $? != 0 ]
-    then
-        echo "Fix PhpStan errors before commit."
-        echo "Run: '$PHPSTAN analyze'"
-        exit 1
+    if [ -f "$CSFIXER" ]; then
+        echo ""
+        echo "Running CS Fixer..."
+
+        php $CSFIXER fix --rules=@PER --dry-run --using-cache=no $FILES
+
+        if [ $? != 0 ]
+        then
+            echo "Fix formatting issues before commit."
+            echo "Run: 'php $CSFIXER fix --rules=@PER --using-cache=no$FILES'"
+            exit 1
+        fi
     fi
 fi
 
-CSFIXER="../../php-cs-fixer.phar"
-
-if [ -f "$CSFIXER" ]; then
-    echo ""
-    echo "Running CS Fixer..."
-
-    eval "php $CSFIXER fix ./ --rules=@PER --dry-run --using-cache=no"
-
-    if [ $? != 0 ]
-    then
-        echo "Fix formatting issues before commit."
-        echo "Run: 'php $CSFIXER fix ./ --rules=@PER --using-cache=no'"
-        exit 1
-    fi
-fi
-
-exit $?
+exit 0
